name: Update Contracts File

on:
  workflow_dispatch:

jobs:
  update_file:
    runs-on: ubuntu-latest  # Or a compatible runner

    steps:
    - uses: actions/checkout@v3  # Checkout the code

    # Install required library (replace 'office365-rest-python-client' with the actual library name if different)
    - name: Install dependencies
      run: pip install office365-rest-python-client

    - name: Download file from SharePoint
      # Use a secure way to store credentials (avoid hardcoding)
      env:
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}  # Consider using a personal access token
      run: |
        python updatefile.py

    - name: Add and commit changes
      run: |
      
        git config --local user.email "andre.scavuzzi@gmail.com"
        git config --local user.name "OMudkip"
        git add ContratosTotais.xlsx
        git commit -m "Update ContractsTotais.xlsx"
        
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GIT_TOKEN}}
        branc: main
