name: Update Contracts File

on:
  # Schedule: Run daily at 00:00 (adjust as needed)
  schedule:
    - cron: '0 15 * * *'

jobs:
  update_file:
    runs-on: ubuntu-latest  # Or a compatible runner

    steps:
    - uses: actions/checkout@v3  # Checkout the code

    # Install required library (replace 'office365-rest-python-client' with the actual library name if different)
    - name: Install dependencies
      run: pip install office365-rest-python-client

    - name: Download file from SharePoint
      # Use a secure way to store credentials (avoid hardcoding)
      env:
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}  # Consider using a personal access token
      run: |
        python updatefile.py

    - name: Add and commit changes
      run: |
        git config user.email "andre.scavuzzi@gmail.com"
        git config user.name "OMudkip"
        git add ContratosTotais.xlsx
        git commit -m "Update ContractsTotais.xlsx"
        git push origin main  # Adjust branch name if needed
