name: Update Contracts File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_file:
    runs-on: ubuntu-latest  # Or a compatible runner

    steps:
    - uses: actions/checkout@v3  # Checkout the code

    # Install required library (replace 'office365-rest-python-client' with the actual library name if different)
    - name: Install dependencies
      run: pip install office365-rest-python-client

    - name: Download file from SharePoint
      # Use a secure way to store credentials (avoid hardcoding)
      env:
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}  # Consider using a personal access token
      run: |
        python updatefile.py

    - name: Commit report
      run: |
        git config --global user.name 'OMudkip'
        git config --global user.email 'OMudkip@users.noreply.github.com'
        git pull
        git add ContratosTotais.xlsx
        git commit -m "Update ContractsTotais.xlsx" --allow-empty
        git push origin main
