name: test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_file:
    runs-on: ubuntu-latest  # Or a compatible runner
    steps:
    - uses: actions/checkout@v3  # Checkout the code
    - name: Download file from SharePoint
      # Use a secure way to store credentials (avoid hardcoding)
      env:
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}  # Consider using a personal access token
      run: |
        python updatefile.py
